Remove `simple_html_css`
cph-cachet/research.package pull request #117
Opened 2024-06-06 13:29 UTC by SlimShadyIAm

The `simple_html_css` package caused build issues when using Flutter 3.22 because some text styling properties were renamed. Although this issue has been fixed in v5.0.0 of the package, it seems that the code that required `simple_html_css` is not called anywhere, so this package can be removed.

2024-06-06 19:03 UTC, albermoon commented
Deleted the package and the widget which used the package are the best option if is unused and it didn't make sense to keep them in the project

2024-06-07 06:52 UTC, bardram requested changes
Is this correct? You can't just remove the InstructionText and Title widgets? You still need to show these even though we don't allow for using HTML? So I guess these build methods should still return the "else" part of the if statement?

2024-06-07 08:54 UTC, SlimShadyIAm commented
As far as I can see, the removed `InstructionText` widget was previously used to render text within the `RPUIInstructionStep`: 

https://github.com/cph-cachet/research.package/blob/5e7eedf4468f9c2de40669404ce090460c7cf92f/lib/src/ui/RPUIInstructionStep.dart#L59-L61

However, currently on master it is rendered using the `Text` widget:

https://github.com/cph-cachet/research.package/blob/f8dcd7968a3f0477a408bfd6c35448ab00ccf785/lib/src/ui/instruction_step.dart#L62-L66

---

Similarly for the removed `Title` widget, when it was added:

https://github.com/cph-cachet/research.package/blob/5e7eedf4468f9c2de40669404ce090460c7cf92f/lib/src/ui/RPUIQuestionStep.dart#L89

vs. on master: 
https://github.com/cph-cachet/research.package/blob/f8dcd7968a3f0477a408bfd6c35448ab00ccf785/lib/src/ui/question_step.dart#L141-L145

2024-06-07 10:05 UTC, bardram approved these changes

2024-06-07 10:49 UTC, merged