New media type support
cph-cachet/research.package pull request #128
Opened 2024-09-25 14:19 UTC by Panosfunk

New media type is supported in the instructions step.
That can be achieved by adding 
- "image_path": "url"
- "audio_path": "url"
- "video_path": "url"

2024-10-09 12:31 UTC, bardram commented
The example app throws an error when running:

<img width="1161" alt="image" src="https://github.com/user-attachments/assets/6a22ea8c-a46c-4065-a58b-2f750cad5322">

2024-10-09 12:35 UTC, bardram commented
When showing a picture, it is way too small...?????

2024-10-09 12:45 UTC, bardram commented
The PLAY button is not shown on audio....

2024-10-09 12:55 UTC, bardram requested changes
All three media types fails or have errors.....

2024-10-11 12:01 UTC, Panosfunk commented
> The PLAY button is not shown on audio....
> 
> ![2024-10-09 14 43 51](https://private-user-images.githubusercontent.com/1196642/374964102-50e3eca4-18fe-487d-b56e-b33f8a233b0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDgyODQsIm5iZiI6MTcyODY0Nzk4NCwicGF0aCI6Ii8xMTk2NjQyLzM3NDk2NDEwMi01MGUzZWNhNC0xOGZlLTQ4N2QtYjU2ZS1iMzNmOGEyMzNiMGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTE1OTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTRhM2I5YWI1N2E5OWM1YzZiNWFjODU2MThjNGRhOTg0Mzk3OGRlZWY2ZjM2NDA1MDFjYWI5MGIwOTI1YzkzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f6hiZZ0WRBIbJXSYMHVE0PwzLvYbkV1-Z-hnlcLazwk)

fixed

2024-10-21 08:53 UTC, Panosfunk commented
> When showing a picture, it is way too small...?????
> 
Fixed

2024-10-21 08:54 UTC, Panosfunk commented
> All media types should support assets as well

Fixed

2024-10-21 09:08 UTC, Panosfunk commented
> The example app throws an error when running:
> 
Fixed

2025-04-08 11:00 UTC, Panosfunk commented
Closes #122

2025-04-15 11:54 UTC, iarata commented
@Panosfunk can you also update the branch to resolve the conflicts

2025-04-15 11:58 UTC, Panosfunk commented
> @Panosfunk can you also update the branch to resolve the conflicts

Yes I'll have that in mind, it's an old PR 😄

2025-04-15 12:00 UTC, Panosfunk commented
I should also fix line in .gitignore that was probably deleted by accident

2025-11-13 12:57 UTC, closed without merging