fixing theme for 'Next' button in tasks
cph-cachet/research.package pull request #94
Opened 2024-01-11 16:34 UTC by Panosfunk

The text on the 'Next' button disappeared when user selected one of the options

2024-01-12 14:51 UTC, bardram requested changes

2024-01-15 08:27 UTC, Panosfunk commented on lib/src/ui/RPUITask.dart
> +                                style: const TextStyle(color: Colors.white),
<img width="272" alt="Screenshot 2024-01-15 at 09 26 01" src="https://github.com/cph-cachet/research.package/assets/36935711/bd72ee60-cf0d-426b-aa1a-4c6403d901c7">
<img width="260" alt="Screenshot 2024-01-15 at 09 26 31" src="https://github.com/cph-cachet/research.package/assets/36935711/51019715-503c-4557-a97e-f4fa55397c12">

2024-01-15 11:10 UTC, bardram commented
ok - seems like this is the best solution, given the other buttons. Let's do it like this.

2024-01-15 11:11 UTC, bardram approved these changes

2024-01-15 11:11 UTC, merged

2024-01-15 14:44 UTC, bardram commented
Has been released in `research_package 1.4.1`.